.TH SEATURTLE 1 "2019-3-27" "V1.0"

.SH NAME
SeaTurtle \- A simple shell built in python3.7.2

.SH SYNOPSIS
.B python3 myshell.py
.IR file 

.SH DESCRIPTION
.B python3 myshell.py
opens the shell

.SH OPTIONS
.IR file
executes the commands given in the batch file and quits after completing them.

.SH "SHELL COMMANDS"
.BI dir 
.IR path/to/directory
.IP
Returns the contents of the given directory, or prints the current directory if no argument is given.

.BI clr
.IP
Clears the terminal

.BI echo
.IR comment
.IP
Prints the comment back out to the terminal

.SH AUTHOR
Sean Moloney
